### ISSUE TITLE
IP address of the crawler should be logged

### ISSUE THREAD

**Issue by bortzmeyer** [451hackathon/block-crawler#4]
Since censorship is heavily dependent on your connection, the JSON report sent to the controller should include the IP address of the machine the crawler was running on.

Since the machine may run on an IPv4 box with private IP addresses and NAT, may be we should log the result of http://icanhazip.com/ as well.

**Comment by atoker** [comment]
Fixed in a2a8cc7faf56907f66bf2a988183173413f60949 using an external discovery service. Probably the most reliable way to get the correct IP (with caveat in the FIXME)
